#!/usr/bin/env python3
"""Generate the dashboard's durable defaults and SQLite contract from Python.

Run after an intentional DEFAULT_STATE, SQLite metadata, or retention change.
The offline test suite checks this artifact; dashboard deployments include it
without requiring Python at runtime.
"""

import json
from pathlib import Path
import sys

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from src.state import (  # noqa: E402
    DEFAULT_STATE,
    MAX_DRAFTS,
    REJECTED_DRAFT_GUARDRAIL_COUNT,
    REJECTED_DRAFT_RETENTION_DAYS,
    _DRAFT_CAP_PROTECTED_STATUSES,
)
from src.storage.sqlite_store import _METADATA_JSON_KEYS  # noqa: E402

OUTPUT = REPO / "dashboard/lib/state-contract.js"


def render() -> str:
    contract = {
        "STATE_DEFAULTS": DEFAULT_STATE,
        "METADATA_JSON_KEYS": list(_METADATA_JSON_KEYS),
        "DRAFT_RETENTION": {
            "maxItems": MAX_DRAFTS,
            "rejectedDays": REJECTED_DRAFT_RETENTION_DAYS,
            "rejectedGuardrailCount": REJECTED_DRAFT_GUARDRAIL_COUNT,
            "protectedStatuses": sorted(_DRAFT_CAP_PROTECTED_STATUSES),
        },
    }
    return "// Generated by scripts/gen_state_contract.py. Do not edit by hand.\n\n" + "\n\n".join(
        f"export const {name} = {json.dumps(value, indent=2, ensure_ascii=False)}"
        for name, value in contract.items()
    ) + "\n"


if __name__ == "__main__":
    rendered = render()
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            raise SystemExit("Dashboard state contract is stale; run python scripts/gen_state_contract.py")
    else:
        OUTPUT.write_text(rendered)
