#!/usr/bin/env python3
"""Generate the fixed scenario snapshot. Never fetch prices or rewrite usage."""

import json
from pathlib import Path
import sys

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
from src.two_bot.usage_cost_scenario import CONTRACT_COST  # noqa: E402

OUTPUT = REPO / "dashboard/lib/usage-cost-contract.js"


def render() -> str:
    return (
        "// Generated by scripts/gen_usage_cost_contract.py. Do not edit by hand.\n"
        "export const COST_SCENARIO = " + json.dumps(CONTRACT_COST, indent=2) + "\n"
    )


if __name__ == "__main__":
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != render():
            raise SystemExit(
                "Cost scenario contract is stale; run scripts/gen_usage_cost_contract.py"
            )
    else:
        OUTPUT.write_text(render())
