#!/usr/bin/env python3
"""Generate the dashboard's policy source manifest; --check gates stale builds."""
import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src.editorial.policy import ROOT, source_manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "dashboard/lib/editorial-policy-manifest.js"
    rendered = "// Generated by scripts/gen_editorial_policy.py; do not edit.\nexport const EDITORIAL_POLICY_MANIFEST = " + json.dumps(source_manifest(), sort_keys=True, indent=2) + "\n"
    if args.check:
        if not target.exists() or target.read_text() != rendered:
            raise SystemExit("Editorial policy manifest is stale. Run python scripts/gen_editorial_policy.py")
    else:
        target.write_text(rendered)


if __name__ == "__main__":
    main()
