"""Material GHCN observation/QC revisions and exact affected-claim links.

This is not a daily observation store. Callers retain only accepted record
points, comparators and subsequently changed points used by retained claims.
Published or uncertain-send objects are never rewritten by this module.
"""

from __future__ import annotations

from copy import deepcopy
from datetime import date
import re

from src.data.temperature_evidence import fingerprint
from src.editorial.revisions import draft_identity, has_unresolved_publish, revoke_approval, text_hash
from src.editorial.revisions import fingerprint as durable_fingerprint


def merge_temperature_history(base, incoming):
    """Union immutable revisions, including collisions at reserved conflict IDs.

    ``:conflict:<fingerprint>`` is a reserved suffix generated by this reducer.
    Re-group it before choosing a canonical primary row so a later conflicting
    payload cannot overwrite earlier evidence or depend on writer order.
    """
    groups: dict = {}
    for source in ({} if base is None else base, {} if incoming is None else incoming):
        if not isinstance(source, dict):
            raise ValueError("Malformed temperature revision history")
        for key, value in source.items():
            if not isinstance(key, str):
                raise ValueError("Malformed temperature revision history key")
            root = re.sub(r"(?::conflict:[0-9a-f]{64})+$", "", key)
            groups.setdefault(root, {})[durable_fingerprint(value)] = value
    result: dict = {}
    for key, rows in groups.items():
        for index, revision_id in enumerate(sorted(rows)):
            target = key if index == 0 else f"{key}:conflict:{revision_id}"
            result[target] = deepcopy(rows[revision_id])
    return result


def _mapping(value):
    return value if isinstance(value, dict) else {}


def _raw(draft):
    context = _mapping(draft.get("review_context"))
    two_bot = _mapping(context.get("two_bot"))
    bundle = _mapping(two_bot.get("bundle"))
    return _mapping(bundle.get("raw_signal_dump"))


def _point(event_id, raw):
    evidence = _mapping(raw.get("evidence"))
    station = evidence.get("station_id") or raw.get("station_id")
    valid = evidence.get("valid_date") or raw.get("signal_date")
    if not station:
        match = re.search(r"_([A-Z0-9]{11})_(?:\d{2}_)?(\d{4}-\d{2}-\d{2})$", event_id)
        if match:
            station, valid = match.groups()
    try:
        day = date.fromisoformat(str(valid))
    except ValueError:
        return None
    if not isinstance(station, str) or not re.fullmatch(r"[A-Z0-9]{11}", station):
        return None
    element = "TMIN" if any(token in event_id for token in ("_low_", "_cold_")) else "TMAX"
    return station, day, element


def retained_claims(state):
    claims = []
    for draft in state.get("drafts") or []:
        if not isinstance(draft, dict):
            continue
        event_id = str(draft.get("event_id") or "")
        raw = _raw(draft)
        if not isinstance(raw, dict):
            continue
        point = _point(event_id, raw)
        if point is None:
            continue
        station, day, element = point
        evidence = _mapping(raw.get("evidence"))
        values = _mapping(evidence.get("variables"))
        observation = _mapping(values.get(element))
        claims.append({
            "station_id": station, "valid_date": day.isoformat(), "element": element,
            "draft_id": draft.get("id"), "event_id": event_id,
            "text_sha256": text_hash(draft.get("text", "")),
            "tweet_id": draft.get("tweet_id"), "status": draft.get("status"),
            "reported_value_c": raw.get("new_temp_c", raw.get("today_temp_c", observation.get("value_c"))),
            "reported_previous_c": raw.get("old_record_c"),
            "publication_time_qflag": observation.get("qflag"),
            "baseline": deepcopy(evidence.get("baseline") or {}),
        })
    return claims


def tracked_points(state):
    points = {
        (claim["station_id"], date.fromisoformat(claim["valid_date"]), claim["element"])
        for claim in retained_claims(state)
    }
    for row in (state.get("temperature_history") or {}).values():
        if not isinstance(row, dict) or row.get("kind") != "observation_revision":
            continue
        try:
            points.add((row["station_id"], date.fromisoformat(row["valid_date"]), row["element"]))
        except (KeyError, TypeError, ValueError):
            continue
    return points


def record_observation_revision(state, record, *, retrieved_at, source_revision):
    """Retain one explicitly material point. Repeated identical values are no-op."""
    semantic = {
        "kind": "observation_revision", "source_product": "noaa-ghcn-daily-v2",
        "station_id": record.station_id, "valid_date": record.obs_date.isoformat(),
        "element": record.element, "value_c": record.value_c,
        "mflag": record.mflag, "qflag": record.qflag.strip(), "sflag": record.sflag,
        "observation_time": record.observation_time,
        "deleted": record.action == "delete", "source_accepted": record.to_daily_obs() is not None,
    }
    revision_id = fingerprint(semantic)
    history = state.setdefault("temperature_history", {})
    if revision_id in history:
        return revision_id, False
    previous_ids = sorted(key for key, row in history.items() if isinstance(row, dict)
                          and row.get("kind") == "observation_revision"
                          and all(row.get(field) == semantic[field] for field in ("station_id", "valid_date", "element")))
    history[revision_id] = {
        **semantic, "revision_id": revision_id, "retrieved_at": retrieved_at,
        "source_payload_sha256": source_revision, "previous_revision_ids": previous_ids,
        "publication_time_qc_known": False,
    }
    return revision_id, True


def _invalidate_unpublished_evidence(draft, finding, state):
    """Use P02 identity/history/approval rules without changing approved text."""
    if (draft.get("status") == "posted" or draft.get("tweet_id")
            or has_unresolved_publish(draft, state)):
        return False
    if draft.get("status") not in ("pending", "approved"):
        return False
    def has_receipt(row):
        if not isinstance(row, dict):
            return False
        conflicts = row.get("attempt_conflicts", [])
        return bool(row.get("tweet_id")) or (isinstance(conflicts, list) and any(has_receipt(item) for item in conflicts))
    ledger = _mapping(state.get("publish_ledger"))
    if has_receipt(ledger.get(draft.get("event_id") or draft.get("id"))):
        return False
    if not isinstance(draft.get("revision_history", []), list):
        return False
    raw = _raw(draft)
    if not isinstance(raw, dict) or not isinstance(raw.get("source_revision_findings", []), list):
        return False
    original = {key: deepcopy(draft[key]) for key in (
        "text", "review_context", "review_binding", "approval_binding", "revision_conflicts", "decision_revision",
        "publish_intent_id", "publish_requested_at", "auto_approve_at", "auto_approve_requested_at",
    ) if key in draft}
    original["draft_snapshot"] = deepcopy(draft)
    original.update(draft_identity(draft))
    original.update(invalidated_at=finding["retrieved_at"], reason="verified_source_revision", source_finding_id=finding["finding_id"])
    draft.setdefault("revision_history", []).append(original)
    draft["content_revision"] = original["content_revision"] + 1
    revoke_approval(draft)
    # Keep the already-created intent identity as evidence, while the revoked
    # binding/status prevents its stale queued worker from publishing.
    for key in ("publish_intent_id", "publish_requested_at"):
        if key in original:
            draft[key] = original[key]
    draft.pop("review_binding", None)
    draft["status"] = "pending"
    draft["post_error"] = "Verified source evidence changed; review this draft against the retained revision finding"
    raw.setdefault("source_revision_findings", []).append(deepcopy(finding))
    draft["updated_at"] = finding["retrieved_at"]
    return True


def record_claim_finding(state, claim, *, reason, source_revision, retrieved_at, details,
                         verified_change=False):
    """Link a current source finding to exact retained text, never a correction."""
    semantic = {
        "kind": "affected_claim", "reason": reason, "source_revision": source_revision,
        "claim": deepcopy(claim), "details": deepcopy(details),
        "publication_time_qc_known": claim.get("publication_time_qflag") is not None,
    }
    finding_id = fingerprint({
        "kind": semantic["kind"], "reason": reason, "details": details,
        "claim": {key: claim.get(key) for key in (
            "station_id", "valid_date", "element", "draft_id", "event_id", "text_sha256", "tweet_id",
        )},
    })
    history = state.setdefault("temperature_history", {})
    if finding_id in history:
        return False
    finding = {**semantic, "finding_id": finding_id, "retrieved_at": retrieved_at}
    history[finding_id] = finding
    if verified_change:
        for draft in state.get("drafts") or []:
            if isinstance(draft, dict) and draft.get("id") == claim.get("draft_id") and text_hash(draft.get("text", "")) == claim["text_sha256"]:
                _invalidate_unpublished_evidence(draft, finding, state)
                break
    return True
